version: "3"

services:
    client:
        image: node:14.0.0
        user: node
        working_dir: /home/node
        tty: true
        stdin_open: true
        ports:
            - 0.0.0.0:8080:8080
            - 0.0.0.0:5001:5001
        volumes:
            - ./client:/home/node

    firebase:
        build: ./docker/firebase
        user: node
        working_dir: /home/node
        tty: true
        stdin_open: true
        ports:
            - 0.0.0.0:9005:9005
        volumes:
            - ./firebase:/home/node

    nginx:
        image: nginx:1.19.1
        ports:
            - 8081:80
        volumes:
            - ./client/build:/usr/share/nginx/html
