version: "3"

services:
    server:
        image: node
        user: node
        working_dir: /home/node
        tty: true
        stdin_open: true
        ports:
            - 3000:3000
        volumes:
            - ./server:/home/node

    client:
        image: node
        user: node
        working_dir: /home/node
        tty: true
        stdin_open: true
        ports:
            - 8080:8080
            - 5001:5001
        volumes:
            - ./client:/home/node