version: "3"

services:
    node:
        image: node
        user: node
        working_dir: /home/node
        tty: true
        stdin_open: true
        ports:
            - 8080:8080
        volumes:
            - .:/home/node
